### ISSUE TITLE
undefined method `delete' for nil:NilClass (NoMethodError) on RHEL5.4

### ISSUE THREAD

**Issue by cgb** [auxesis/visage#10]
[root@collectd visage]# bundle install
Installing errand (0.7.0) from .gem files at /var/www/html/visage/vendor/cache with native extensions 
Installing haml (2.2.19) from .gem files at /var/www/html/visage/vendor/cache 
Installing rack (1.1.0) from .gem files at /var/www/html/visage/vendor/cache 
Installing sinatra (0.9.4) from .gem files at /var/www/html/visage/vendor/cache 
Installing yajl-ruby (0.7.0) from .gem files at /var/www/html/visage/vendor/cache with native extensions 
Your bundle is complete!
/usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/definition.rb:87:in `dependencies': undefined method`delete' for nil:NilClass (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/definition.rb:86:in `map'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/definition.rb:86:in`dependencies'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb:50:in `dependencies'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/environment.rb:15:in`group_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb:95:in `specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb:174:in`specs_for_lock_file'
    from (erb):12:in `write_rb_lock'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb:139:in`write_rb_lock'
     ... 13 levels...
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/vendor/thor.rb:124:in `start'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/bin/bundle:11
    from /usr/bin/bundle:19:in`load'
    from /usr/bin/bundle:19

Similarly, via passenger:
Error message:
    undefined method `delete' for nil:NilClass
Exception class:
    NoMethodError
Application root:
    /var/www/html/visage 

0   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/definition.rb     87      in `dependencies'
1   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/definition.rb     86  in`map'
2   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/definition.rb     86  in `dependencies'
3   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    50  in`dependencies'
4   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/environment.rb    15  in `group_specs'
5   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    95  in`specs'
6   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    174     in `specs_for_lock_file'
7   (erb)   12  in`write_rb_lock'
8   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    139     in `write_rb_lock'
9   /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    138     in`open'
10  /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    138     in `write_rb_lock'
11  /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler/runtime.rb    10  in`initialize'
12  /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler.rb    76  in `new'
13  /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler.rb    76  in`load'
14  /usr/lib/ruby/gems/1.8/gems/bundler-0.9.5/lib/bundler.rb    66  in `setup'
15  config.ru   10  
16  /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/vendor/rack-1.0.0-git/lib/rack/builder.rb   29  in`instance_eval'
17  /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/vendor/rack-1.0.0-git/lib/rack/builder.rb   29  in `initialize'
18  config.ru   1   in`new'
19  config.ru   1

**Comment by auxesis** [comment]
Hmm ok, looks like the new version of bundler has broken everything _again_.

**Comment by auxesis** [comment]
I should add, I've tested the current bundler configuration with bundler 0.9.3, but nothing higher. If you want to get up and running quickly, you need to be using 0.9.3.

**Comment by cgb** [comment]
Hi there,

Yup, 0.9.3 succesfully installed the required components..  I'm experiencing another problem now whether graphs are not being generated.  The web interface is browseable but when it comes to selecting a graph profile, I see the graph heading (e.g. 'load on <hostname>') but the graphs don't show, and the apache error_log shows:

[Sun Feb 14 17:41:42 2010] [error] [client 192.168.1.54] Premature end of script headers: data, referer: http://collectd.myserver/clienthostname/load

Any ideas?

**Comment by chaslemley** [comment]
Your original issue may be from locking a Bundle Environment using Bundler 0.9.3 and then trying to use it with Bundler 0.9.5 try unlocking it, installing the new version of Bundler and then working with it.

**Comment by auxesis** [comment]
Thanks for the tip!

**Comment by auxesis** [comment]
Latest HEAD should fix this problem. Re-open if it's still a problem!
