### ISSUE TITLE
Profile Saved flash is hidden when head nav has scrolled off the screen

### ISSUE THREAD

**Issue by jessereynolds** [auxesis/visage#100]
If you are down the bottom of a long list of metrics, you give the profile a name and click Save, you don't see the "Profile Saved" flash message as I think it's appearing at the top of the page, even when the top of the page has scrolled off the top of the browser window. So there is no feedback you can see that the profile save has been successful. 

This is on visage 2.1.0.

**Comment by auxesis** [comment]
The save feedback in 3.0 displays in the Share modal dialog, so the behaviour in this issue no longer occurs. 

Closing.
