### ISSUE TITLE
Creating Profiles 

### ISSUE THREAD

**Issue by msacks** [auxesis/visage#104]
I am trying to create a profile so I can begin monitoring my collectd metrics. I tried doing this through the Web interface on :9292 but I am not exactly sure what to put. Do I need to configure the hosts and profiles in profiles.yaml first?

What is the format for this file?

Thanks,
Matt

**Comment by jessereynolds** [comment]
Use the web interface, it writes out the profiles.yaml when you add new profiles. 

Start by entering some of the letters in one of your hosts, then use the arrow and return keys to select the host(s) you want to add. Use down arrow to get the list to appear. You can add as many as you like. 

Then tab over to the metrics column and do the same thing there. Then click Show Graphs. When you're happy, enter a name for the profile and save it. It'll then add it to the profiles.yaml file. 

Currently you can't change the name of profiles, or delete them, through the web interface. You can however do this by hacking the profiles.yaml file (but be careful).
