### ISSUE TITLE
nothing in public dir / accessing rrd via json

### ISSUE THREAD

**Issue by msacks** [auxesis/visage#105]
I am a bit slow due to beginner familiarity with ruby, and there isn't a lot of documentation on visage, which seems to be an excellent utility. 

It seems there is an admin interface and a public site (port 80) to visage, is that correct? The admin interface being on port :9292 and the public site which was created via visage-app genapache call. Is that correct?

Currently the only items in my ./public directory are source files (js, css) but no site. 

I'm wondering if I have something configured improperly and also how can I access rrd information via json?

Thank you,
Matt

**Comment by jessereynolds** [comment]
I'm not sure about the genapache call, but you can either run visage-app standalone and it will have it's admin and 'public' interface on port 9292 (or whatever you customise), or you can put it behind a web server and it'll be on port 80 or whatever port your webserver is listening on. 

Note that there is no separate admin and public interfaces. Anyone who has access to visage has access to edit and create profiles as well (unless you make profiles.yaml not writeable by the visage process, but that will yield ugly errors to the user).

**Comment by auxesis** [comment]
@msacks: I'm guessing you don't have Passenger (mod_ruby) installed. 

On Ubuntu or Debian you can install it with: 

```
sudo apt-get install libapache2-mod-passenger
```

On CentOS,RHEL,Fedora, follow [the guide provided by Phusion](http://www.modrails.com/documentation/Users%20guide%20Apache.html#_installing_or_upgrading_on_red_hat_fedora_centos_or_scientificlinux). 

After installing Passenger, the Apache vhost should work.
