### ISSUE TITLE
display of large numbers converted to Mega and Giga using 1024*n as divisor

### ISSUE THREAD

**Issue by jessereynolds** [auxesis/visage#106]
Visage seems to be using x/1024*n to get up to Gigahertz (treating it like it's Gigabytes)
7419199488 hertz == 6.91G ? Not really.

This is probably what you'd want when showing bytes, but all other high values should use x/1000n to convert to Mega, Giga etc.

**Comment by jessereynolds** [comment]
In the formatValue function here: https://github.com/auxesis/visage/blob/master/lib/visage-app/public/javascripts/graph.js#L107-141

**Comment by auxesis** [comment]
Per a conversation with @jessereynolds, I've changed the default value formatting from base 2 to base 10, as base 2 formatting seems to be required in the minority of cases. 

dd2521a7f1ac9d0c1aa47820881ab4efcd745d37 also add support for specifying the base you render with, which will be useful for nicely converting network device octets to megabytes.
