### ISSUE TITLE
Can not run on fedora 8

### ISSUE THREAD

**Issue by yingfeng** [auxesis/visage#11]
Hi,
I install rrdtool on fedora 8. The version of rrdttool and rrd-devel is 1.3.4.
And I directly install rubyrrdtool from git sources.
After I start visage, here are the error info:
LoadError: /usr/local/lib/ruby/site_ruby/1.8/x86_64-linux/errand_backend.so: undefined symbol: rrd_resize - /usr/local/lib/ruby/site_ruby/1.8/x86_64-linux/errand_backend.so

Therefore I comment the cooresponding parts of rrd_resize in rrdtool_main.c, then other interfaces
of rrdtool can still not be found. 

I guess something must be wrong on my local configuration, but I can not figure it out. Could you provide some suggestion? Thanks

**Comment by yingfeng** [comment]
I got the solution.
I need to change this line in extconf.rb
dir_config("rrd")
to
dir_config("rrd","/usr/lib","/usr/local/lib")

Then rebuild rrdtool, then everything is ok

**Comment by auxesis** [comment]
Ah great. That line you changed was in the Errand gem?

You might want to check out #7, and [my rant](http://mailman.verplant.org/pipermail/collectd/2010-February/003597.html) on the collectd mailing list. 

For the time being I'm going to refactor Errand to just use the Ruby library packaged in your distro.
