### ISSUE TITLE
Alter behaviour of builder UI around profile options and name

### ISSUE THREAD

**Issue by jessereynolds** [auxesis/visage#111]
The profile name field and the save button should form part of the Profile Options. 

The whole Profile Options section can be hidden (like the profile name and save button are now) until after you've clicked 'Show Graphs'

The save button should be visible but greyed out until some of the profile options have been modified (timeframe, 95th percentile, profile name)

We discussed changing Profile Options to "Global Options" but in retrospect I think this would be confusing as users may think they are options being set for the visage instance, to be used across all profiles. 

Currently there's a bug if you edit a profile with a view to changing the timeframe, you have to first click Show Graphs before the Timeframe selector will work. This should magically disappear after implementing the above.

**Comment by auxesis** [comment]
Agree with everything above. 

I think we should rename "Profile Options" to "Profile Settings".

**Comment by jessereynolds** [comment]
I've renamed it to Profile Settings, and fixed a bug mentioned in the last paragraph (editing timeframes of a profile).

**Comment by auxesis** [comment]
This behaviour is significantly different in Visage 3.0. 

Closing this issue, but feel free to open up a new one to discuss issues with the 3.0 way of doing things.
