### ISSUE TITLE
Sort charts by title on profile page

### ISSUE THREAD

**Issue by jdub** [auxesis/visage#113]
Charts on a profile page displayed in following order:

disk-sdb
cpu-0
cpu-3
cpu-2
cpu-1

It would probably make sense to sort them by title, if sort order not otherwise defined.

**Comment by auxesis** [comment]
In Visage 3.0 the graphs can be re-ordered by dragging them. 

Closing.

**Comment by jdub** [comment]
Manual reordering is not quite the same as having a good default sort order. :-)
