### ISSUE TITLE
Munin data source

### ISSUE THREAD

**Issue by gindox** [auxesis/visage#114]
It would be good to be able to extent visage to point to a munin data source structured this way

+-- server01
¦   +-- server01-cpu-idle.rrd
¦   +-- server01-cpu-interrupt.rrd
¦   +-- server01-cpu-nice.rrd
+-- another_serv
¦   +-- another_serv-cpu-idle.rrd
¦   +-- another_serv-cpu-interrupt.rrd
¦   +-- another_serv-cpu-nice.rrd

The collectd structure is structured diferently

+-- server01
    +-- cpu-0
    ¦   +-- cpu-idle.rrd
    ¦   +-- cpu-interrupt.rrd
    +-- df
    ¦   +-- df-run.rrd
    ¦   +-- df-run-shm.rrd
    +-- disk-xvda1
    ¦   +-- disk_merged.rrd

**Comment by auxesis** [comment]
Hey @gindox, this will be really easy to implement in Visage 3.0. 

3.0 has the concept of pluggable data backends. You only need to implement the following methods on your backend: 

| method name | arguments | type |
| :-- | :-- | :-- |
| json | `opts={}` | instance |
| hosts | `opts={}` | class |
| metrics | `opts={}` | class |

For some example data backends, check out the [RRD](https://github.com/auxesis/visage/blob/master/lib/visage-app/data/rrd.rb) and [Mock](https://github.com/auxesis/visage/blob/master/lib/visage-app/data/mock.rb) backends. 

You should be able to adapt the existing RRD backend to use the munin directory structure pretty easily. 

Let me know if you need any help with this, and I look forward to reviewing your Pull Request. :blush:
