### ISSUE TITLE
please update dependencies

### ISSUE THREAD

**Issue by swills** [auxesis/visage#115]
Hi,

Could you please update the dependencies to:

errand ~> 0.7
haml ~> 3.1
sinatra ~> 1.3
tilt ~> 1.3
yajl-ruby ~> 1.1

This will allow packaging with newer versions of these depends.

Thanks,
Steve

**Comment by auxesis** [comment]
I have tackled this in 4f3de39ccc689e09a8fbd84195bb66968d4bf620. 

This will be released in Visage 3.0.
