### ISSUE TITLE
No such file or directory - /usr/share/collectd/types.db (Errno::ENOENT)

### ISSUE THREAD

**Issue by phillashworth** [auxesis/visage#126]
Trying to get visage running on FreeBSD and get the following error.
# visage-app start

/usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app/types.rb:19:in `initialize': No such file or directory - /usr/share/collectd/types.db (Errno::ENOENT)
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app/types.rb:19:in`new'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app/types.rb:19:in `build'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app/types.rb:10:in`initialize'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app.rb:34:in `new'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app.rb:34
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app/config.rb:6:in`use'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app.rb:31
    from /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:1273:in `configure'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/lib/visage-app.rb:30
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/visage-app-2.1.0/bin/visage-app:17
    from /usr/local/bin/visage-app:23:in`load'
    from /usr/local/bin/visage-app:23

**Comment by jessereynolds** [comment]
Yep, Visage assumes your collectd installation has types.db in that location. You could probably get away with symlinking it. 

Version 3 will not require types.db I am led to believe...

**Comment by phillashworth** [comment]
symlink does the trick thanks

**Comment by jessereynolds** [comment]
Great
