### ISSUE TITLE
lighttpd

### ISSUE THREAD

**Issue by swasher** [auxesis/visage#127]
Please describe how to manage Visage with lighttpd. Wiki article will be excellent!

**Comment by auxesis** [comment]
Hi @swasher,
Deploying Visage with lighttpd isn't really any different to deploying any Rails, Sinatra, or Rack application on lighttpd. 

I can highly recommend these articles: 
- [Mixing it up with lighttpd and Sinatra](http://agilesysadmin.net/lighttpd-sinatra)
- [Deploying Sinatra via Thin and Lighttpd](http://www.gittr.com/index.php/archive/deploying-sinatra-via-thin-and-lighttpd/)

The only thing you would need to change is the backend servers you use: 

```
        proxy.server =  ("/" =>
                                (
                                        ( "host" => "127.0.0.1", "port" => 9292 ),
                                )
                        ) 
```

Then start up `visage-app` using the normal command line, and you should be good to go!

If you could turn the above into a wiki article, I'd be very happy to review!
