### ISSUE TITLE
after installing visage-app, when I try to start it,  I get :   cannot load such file -- RRD (LoadError)

### ISSUE THREAD

**Issue by litebito** [auxesis/visage#128]
system info :
- Ubutnu LTS 12.04
- collectd installed via apt-get 
  (from  https://launchpad.net/~vbulax/+archive/collectd5 )
  which installes following : 

libcollectdclient1_5.2.0-2ubuntu1_i386.deb
libcollectdclient-dev_5.2.0-2ubuntu1_i386.deb
collectd-dev_5.2.0-2ubuntu1_all.deb
collectd_5.2.0-2ubuntu1_i386.deb
collectd-utils_5.2.0-2ubuntu1_i386.deb
collectd-core_5.2.0-2ubuntu1_i386.deb
(including dependencies)

after installation, directories
/var/lib/collectd
/usr/include/collectd/
/usr/lib/collectd
/usr/share/collectd/
- following instructions, installed rrd-ffi & visage-app

**\* LOCAL GEMS ***

activesupport (3.2.12)
bundler (1.3.2)
daemon_controller (1.1.2)
errand (0.7.3)
fastthread (1.0.7)
ffi (1.4.0)
haml (3.1.4)
i18n (0.6.4)
multi_json (1.6.1)
passenger (3.0.19)
rack (1.5.2)
rack-protection (1.5.0)
rake (10.0.3)
rrd-ffi (0.2.14)
rubygems-bundler (1.1.1)
rvm (1.11.3.6)
sinatra (1.3.2)
tilt (1.3.3)
visage-app (2.1.0)
yajl-ruby (1.1.0)

results in :
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app/
- this is the trace 

/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require': cannot load such file -- RRD (LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/errand-0.7.3/lib/errand.rb:4:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app/collectd/json.rb:6:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app.rb:14:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/bin/visage-app:17:in '<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/visage-app:19:in 'load'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/visage-app:19:in '<main>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in 'eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in '<main>'

What am I still missing ?

Thanks

**Comment by swasher** [comment]
```
$ apt-get install librrd-dev librrd-ruby1.9.1
```

**Comment by litebito** [comment]
Hi,

thanks for the quck answer

I tried that just now:

apt-get install librrd-dev librrd-ruby1.9.1
Reading package lists... Done
Building dependency tree  
Reading state information... Done
librrd-dev is already the newest version.
The following NEW packages will be installed:
  librrd-ruby1.9.1 libruby1.9.1
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 4,223 kB of archives.
After this operation, 13.0 MB of additional disk space will be used.
Get:1 http://be.archive.ubuntu.com/ubuntu/ precise-updates/main libruby1.9.1 i386 1.9.3.0-1ubuntu2.5 [4,210 kB]
Get:2 http://be.archive.ubuntu.com/ubuntu/ precise/main librrd-ruby1.9.1 i386 1.4.7-1 [12.5 kB]
Fetched 4,223 kB in 0s (4,766 kB/s)  
Selecting previously unselected package libruby1.9.1.
(Reading database ... 105130 files and directories currently installed.)
Unpacking libruby1.9.1 (from .../libruby1.9.1_1.9.3.0-1ubuntu2.5_i386.deb) ...
Selecting previously unselected package librrd-ruby1.9.1.
Unpacking librrd-ruby1.9.1 (from .../librrd-ruby1.9.1_1.4.7-1_i386.deb) ...
Setting up libruby1.9.1 (1.9.3.0-1ubuntu2.5) ...
Setting up librrd-ruby1.9.1 (1.4.7-1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place

but sadly, that does nor resolve the issue

WB

**Comment by auxesis** [comment]
@wikibit are you still getting the same exception + backtrace, or are you getting another error now?

@swasher :+1: thanks for the helping hand! Do you think we should add this to Visage's install instructions?

**Comment by litebito** [comment]
Hi,

I'm still getting the same exception + backtrace

WB

**Comment by swasher** [comment]
@wikibit You have ruby 1.9.3 and install librrd-ruby1.9.1. May be it's a trouble with path? Mine visage have path `/var/lib/gems/1.9.1/gems/visage-app-2.1.0` on Ubuntu 12.10

**Comment by litebito** [comment]
hmmm maybe (I'm not a ruby expert :( )
but there is no other librrd (for ruby 1.9.1)

as far as I can follow, visage-app uses errandb.rb ? 
 /usr/local/rvm/gems/ruby-1.9.3-p392/gems/errand-0.7.3/lib/errand.rb:4:in '<top (required)>'
which then cannot find "RRD"

there is a slight different error if I use the suggestion from the site of visage-app itself:
visage-app start
or
$(dirname $(dirname $(gem which visage-app)))/bin/visage-app start

~$ visage-app start
/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require': cannot load such file -- RRD (LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/errand-0.7.3/lib/errand.rb:4:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app/collectd/json.rb:6:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app.rb:14:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/bin/visage-app:17:in '<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/visage-app:19:in 'load'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/visage-app:19:in '<main>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in 'eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in '<main>'
~$ $(dirname $(dirname $(gem which visage-app)))/bin/visage-app start

/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require': cannot load such file -- RRD (LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/errand-0.7.3/lib/errand.rb:4:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in 'rescue in require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app/collectd/json.rb:6:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/lib/visage-app.rb:14:in '<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/visage-app-2.1.0/bin/visage-app:17:in '<main>'
~$

**Comment by skorfmann** [comment]
I have the same issue (same OS, but rbenv). I've tried everything from above and still get the same backtrace. Any ideas?

**Comment by frdmn** [comment]
@skorfmann i had the same problem, expect that i run ruby via rvm. 

I fixed it with "gem install librrd".

**Comment by litebito** [comment]
@frdmn thanks, that also fixed this for me!

**Comment by vicendominguez** [comment]
One extra point: in FreeBSD you will need to compile rrdtool with Ruby support. Remember to do a "make config" first in you are using the "ports".

**Comment by juandx** [comment]
@frdmn thanks a lot, that also fixed this for me! I‘m new to rrdtool
