### ISSUE TITLE
Visage Performance very slow

### ISSUE THREAD

**Issue by bryanforst** [auxesis/visage#129]
I installed visage on an Ubuntu box, its our production so it has plenty of cpu and memory, but the performance is very very slow. At least 30 seconds for the first display of the profile page (3 profiles currently). Very long wait for the list of graphs, long wait to save a profile, etc. 

The first graph I did was for free memory and it seems as soon as Visage is started the system loses 700mb of memory,  before any graphs are generated. 

Have not seen any posts on performance problems. Has anyone seen this type of behavior?

Here is the first bit of the startup log, :

```
Looking for RRDs in /var/lib/collectd/rrd

[2013-03-21 02:42:46] INFO  WEBrick 1.3.1
[2013-03-21 02:42:46] INFO  ruby 1.8.7 (2010-08-16) [i486-linux]
[2013-03-21 02:42:51] INFO  WEBrick::HTTPServer#start: pid=8711 port=9292
202.144.184.147 - - [21/Mar/2013:02:43:27 PDT] "GET / HTTP/1.1" 302 0
- -> /
202.144.184.147 - - [21/Mar/2013:02:43:42 PDT] "GET /profiles HTTP/1.1" 200 2521
- -> /profiles
```

**Comment by auxesis** [comment]
Have you had any luck running this on Ruby 1.9 (preferably 1.9.3)?

What's your operating system? Do other Ruby applications exhibit similar behaviour?

My hunch is that this is a memory leak in the RRDtool plugin.

**Comment by bryanforst** [comment]
Ive updates the various packages on this machine and Visage performs in a
reasonable fashion now. Apparently some combination of software versions
was causing the problem ....

On Mon, Jul 29, 2013 at 3:10 AM, Lindsay Holmwood
notifications@github.comwrote:

> Have you had any luck running this on Ruby 1.9 (preferably 1.9.3)?
> 
> What's your operating system? Do other Ruby applications exhibit similar
> behaviour?
> 
> My hunch is that this is a memory leak in the RRDtool plugin.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/auxesis/visage/issues/129#issuecomment-21695065
> .

## 

---

bryanforst@gmail.com
mobile: +856 020 7764 7338

**Comment by auxesis** [comment]
Interesting! 

If it pops up again, please let me know. 

Thanks for taking the time to reply, especially after such a long delay.
