### ISSUE TITLE
Vertical axis on graph is wrong

### ISSUE THREAD

**Issue by jamtur01** [auxesis/visage#13]
A number of graphs have massive numbers as vertical axis scales.  The axis is correct when you drill down and select a subset of data.

**Comment by trinary** [comment]
Seeing this as well.  Hitting the "show" button appears to fix it, sometimes.  No odd-looking data in the source rrds.

**Comment by auxesis** [comment]
Can reproduce. 

This is an RRD -> Ruby bug. A quick fix here I have to implement is to filter the weird data in Errand before serving it up.

**Comment by auxesis** [comment]
[Fixed](http://github.com/auxesis/visage/commit/35cd6e368732a703e66485b995182c8d7ba2547f).
