### ISSUE TITLE
Problem with apachegen

### ISSUE THREAD

**Issue by stetho** [auxesis/visage#130]
I have two problems with my install of Visage but I'm pretty sure they're unrelated so I'm going to post them as separate issues.

When I run the apachegen command the config that is generated contains the line

DocumentRoot /var/lib/gems/1.9.1/gems/visage-app-2.1.0/lib/lib/visage-app/public

Which contains two /lib - one more than the actual path:

/var/lib/gems/1.9.1/gems/visage-app-2.1.0/lib/visage-app/public

Easy to fix with a text editor but took me about an hour to spot (looking in the wrong places!)

**Comment by abuisine** [comment]
samething here on visage 2.1.0
