### ISSUE TITLE
Problem with time zones - I think!

### ISSUE THREAD

**Issue by stetho** [auxesis/visage#131]
I have two problems with my install of Visage but I'm pretty sure they're unrelated so I'm going to post them as separate issues. This is problem 2.

I'm having problems with the graphs being drawn but can't figure out where the problem is coming from. I've attached a screenshot below that shows the VM running Apache/Visage/CollectD (top) and my computer (botton) are both set to BST but that the graphs are drawing the most recent point as an hour ago (middle).

Is there another time zone setting I'm missing or some obscure configuration issue?

![Screen Shot 2013-04-24 at 17 43 06](https://f.cloud.github.com/assets/58514/421061/2a72e90c-acff-11e2-93e3-f4797e5b9669.png)

**Comment by jessereynolds** [comment]
Visage currently uses UTC on the X axis. However it also uses your local time when hovering over data points.
