### ISSUE TITLE
Docs for embedding?

### ISSUE THREAD

**Issue by yanosz** [auxesis/visage#136]
Hello,

I'm looking for docs on http://visage.unstated.net/nadia/network - how can I integrate visage into existing webpages using predefined profiles?

Thanks, 
yanosz

**Comment by auxesis** [comment]
Hi there. 

For now, my suggestion is to use Visage's [JSON API](https://github.com/auxesis/visage/blob/master/man/visage-api.5.ronn) to pull the data, and then graph it yourself using something like nvd3 or Highcharts. 

Previously there was functionality to embed the graphs, however it never really worked that well, and has been removed as part of 3.0. 

I will take another look at adding this back in a future release (3.1+), but for now your best bet is to consume the API and draw your own graphs. 

Alternatively, you could use an iframe?

Good luck, and please don't hesitate to comment in this or other issues if you need help!
