### ISSUE TITLE
All of the below

### ISSUE THREAD

**Issue by johnf** [auxesis/visage#137]
In the builder, it would be great to have an "all of the below" selector as a complement to "all of the above". Eliminates a lot of scrolling when needing to add say cpu graphs on an 8 CPU machine.

**Comment by auxesis** [comment]
Hey @johnf - is this on Visage 2 or 3?


## 

w: http://holmwood.id.au/~lindsay/
t: @auxesis

**Comment by johnf** [comment]
Pretty sure that's in 2. So not sure if it is relevant in 3

**Comment by auxesis** [comment]
Alright. The builder is completely different in 3.0, so your problem may be
gone there.

I'm not going to sink any more time into fixing 2.x releases, so best check
out what's happening in 3.0 and report bugs against it.

## 

w: http://holmwood.id.au/~lindsay/
t: @auxesis

**Comment by johnf** [comment]
Cleaning up some old issues I own
