### ISSUE TITLE
Documentation doesn't mention installing librrd-ruby

### ISSUE THREAD

**Issue by misaka** [auxesis/visage#15]
I needed to install librrd-ruby on my ubuntu machine to satisfy errand, technically this should be an errand issue but I didn't see a way to add an issue there. The documentation is generally useful but I spent a bit of time tracking this down, it may be worth adding it.

**Comment by auxesis** [comment]
Yep this is a totally valid point. If you have time, would you mind adding it to `README.md` and submitting a pull request?

Don't worry about making it perfect, I'll clean it up before merging.

**Comment by auxesis** [comment]
I've fixed this in [d1051c](http://github.com/auxesis/visage/commit/d1051c7eafce57de6eeda06295c35851dbba4dff#diff-0).
