### ISSUE TITLE
Issues compiling RubyRRDtool

### ISSUE THREAD

**Issue by retr0h** [auxesis/visage#2]
What am i doing wrong?

I have the app on my server.  I ran rake deps, which froze the gems under the gems/ dir.
When running the app under passenger I get the following:  I do not see the application
setting the gems path to visage/gems/.  Should the gems be installed as system wide gems?

Error message:
no such file to load -- RRDtool
Exception class:
LoadError
Application root:
/var/www/sites/u/apps/visage

**Comment by retr0h** [comment]
Ahh it's a problem with RubyRRDtool compiling on ubuntu.  Haven't tracked it down yet.

gothcandy% make
cc -I. -I. -I/usr/lib/ruby/1.8/x86_64-linux -I.  -fPIC -fno-strict-aliasing -g -g -O2  -fPIC  -DHAVE_RRD_DUMP_R_2  -c rubyrrdtool.c
In file included from rubyrrdtool.c:25:
rrd_addition.h:20: error: redeclaration of enumerator 'RD_I_VAL'
/usr/include/rrd.h:95: error: previous definition of 'RD_I_VAL' was here
rrd_addition.h:21: error: redeclaration of enumerator 'RD_I_CNT'
/usr/include/rrd.h:96: error: previous definition of 'RD_I_CNT' was here
rrd_addition.h:22: error: redeclaration of enumerator 'RD_I_STR'
/usr/include/rrd.h:97: error: previous definition of 'RD_I_STR' was here
rrd_addition.h:23: error: redeclaration of enumerator 'RD_I_INT'
/usr/include/rrd.h:98: error: previous definition of 'RD_I_INT' was here
rrd_addition.h:39: error: conflicting types for 'rrd_info'
/usr/include/rrd.h:122: error: previous declaration of 'rrd_info' was here
rubyrrdtool.c: In function 'rrdtool_create':
rubyrrdtool.c:317: warning: passing argument 5 of 'rrd_create_r' from incompatible pointer type
rubyrrdtool.c: In function 'rrdtool_update':
rubyrrdtool.c:590: warning: passing argument 4 of 'rrd_update_r' from incompatible pointer type
make: **\* [rubyrrdtool.o] Error 1

**Comment by retr0h** [comment]
It appears this was fixed in a fork but not rolled back into mainline.

http://github.com/gebi/rubyrrdtool/commit/dace968eee0c323076f1004f494b525176faac02

**Comment by auxesis** [comment]
Ok, so the solution is to install from that branch, and point Visage at it. :-)

**Comment by retr0h** [comment]
With Ubuntu having quite a large following in the ruby world.  Visage would be unusable in it's current state.  Sure, I could point to a fork, but that won't get me entirely there given the way rake deps works.

http://www.linode.com/railsrumble/2009/ (just some stats on what most the guys used in last rails rumble)

**Comment by auxesis** [comment]
Don't disagree, it's pretty fali. I'll have a look at fixing this more thoroughly in the next few days.

**Comment by MrPink** [comment]
just for your information I am experiencing it on Debian 5 also

**Comment by auxesis** [comment]
Thanks for the heads up. Sounds like a lot of people are experiencing the problem - I'll definitely take a poke at it today.

**Comment by hellvinz** [comment]
Hi, I may be wrong but the rubyrrdtool project seems stalled.

The Rrdtool project is providing a builtin ruby library http://oss.oetiker.ch/rrdtool/prog/rrdruby.en.html which can also be found in major distributions:
- http://packages.debian.org/lenny/librrd-ruby1.8 
- http://packages.ubuntu.com/karmic/librrd-ruby

Switching to 'official' ruby library would ease the process of installing Visage, i guess... and code modifications are light, here's the patch to reach the same functionality with the RRD library (ok I'm too lazy to fork):

```
    diff --git a/lib/collectd-json.rb b/lib/collectd-json.rb
    index 81872a3..519bc62 100644
    --- a/lib/collectd-json.rb
    +++ b/lib/collectd-json.rb
    @@ -1,6 +1,6 @@
     #!/usr/bin/env ruby

    -require 'RRDtool'
    +require 'RRD'
     require 'yajl'

     # Exposes RRDs as JSON. 
    @@ -26,7 +26,7 @@ class CollectdJSON
         rrds = {}
         rrdglob = "#{@rrddir}/#{host}/#{plugin}/#{plugin_instance || '*'}.rrd"
         Dir.glob(rrdglob).map do |rrdname|
    -      rrds[File.basename(rrdname, '.rrd')] = RRDtool.new(rrdname)
    +      rrds[File.basename(rrdname, '.rrd')] = rrdname
         end

         encode(opts.merge(:rrds => rrds))
    @@ -42,9 +42,10 @@ class CollectdJSON

         values = { opts[:host] => { opts[:plugin] => {} } }

    -    opts[:rrds].each_pair do |name, rrd|
    -      plugin_instance = rrd.fetch(['AVERAGE', '--start', opts[:start], '--end', opts[:end]])
    -   
    +    opts[:rrds].each_pair do |name, path|
    +      plugin_instance = RRD.fetch(path,'--start',opts[:start].to_i.to_s, '--end',opts[:end].to_i.to_s, 'AVERAGE')
    +      plugin_instance.pop
    +         
           # filter out NaNs, so yajl doesn't choke
           plugin_instance[3].each do |datasets|
             datasets.map! do |datapoint|
```

cheers
Vincent

**Comment by auxesis** [comment]
Hi Vincent,
Firstly, thanks for your patches! I definitely appreciate the contribution. 

I haven't announced it yet, but I've actually taken over the maintainership of the Ruby RRD bindings, and released them under a new project called Errand. You can find the new code at http://github.com/auxesis/rubyrrdtool, and you can install the gem from Gemcutter. 

Your patch goes about 50% of the way to working with Errand, so I'll make sure to integrate it later today.

Thanks again,
Lindsay

**Comment by auxesis** [comment]
Ok, this is fixed in the latest head. Try pulling and running through the install instructions again.
