### ISSUE TITLE
Swap graph not showing:

### ISSUE THREAD

**Issue by jamtur01** [auxesis/visage#21]
This is the URL:

http://visage.puppetlabs.com/apu.puppetlabs.com/swap
profiles.yml:

  Swap:
    plugins:
      - swap/swap-cached/swap-free/swap-used/swap_io-in/swap_io-out
    splat: swap
    order: 3

and ls -l of the rrd directory:

-rw-r--r--  1 root root 148648 May 26 05:30 swap-cached.rrd
-rw-r--r--  1 root root 148648 May 26 05:30 swap-free.rrd
-rw-r--r--  1 root root 148648 May 26 05:30 swap-used.rrd
-rw-r--r--  1 root root 148648 May 26 05:30 swap_io-in.rrd
-rw-r--r--  1 root root 148648 May 26 05:30 swap_io-out.rrd

I can see data in there but nothing gets displayed.  

Do you still have creds to the site?

James

**Comment by auxesis** [comment]
Ok, that's weird. Can you try replacing the `swap/swap-cached.+` with swap?

I don't think I still have the creds, I'll get them from you again (but not via a public bug tracker).

**Comment by jamtur01** [comment]
No joy.  Still broken.

**Comment by auxesis** [comment]
This was a problem with the color detection on `swap_io-in` and `swap_io-out`. I've [fixed the fallback behaviour](http://github.com/auxesis/visage/commit/35cd6e368732a703e66485b995182c8d7ba2547f), and added a [color definition for these two metrics](http://github.com/auxesis/visage/commit/d376bddd316c8d25b5c5d284d8e52524968f30fa).
