### ISSUE TITLE
can't convert Array into String (TypeError)

### ISSUE THREAD

**Issue by ghost** [auxesis/visage#23]
This error shows up when I try to run visage.

Any thoughts ?

```
# visage start
 _    ___
| |  / (_)________ _____ ____
| | / / / ___/ __ `/ __ `/ _ \
| |/ / (__  ) /_/ / /_/ /  __/
|___/_/____/\__,_/\__, /\___/
                 /____/

will be running at http://eniac-01.adm.infra:9292/

/usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/server.rb:228: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/utils.rb:138:in `union': can't convert Array into String (TypeError)
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/utils.rb:138
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:1
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:3
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/handler.rb:37:in `default'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/server.rb:217:in `server'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/server.rb:213:in `start'
        from /usr/lib/ruby/gems/1.8/gems/visage-app-0.2.1/bin/visage:28
        from /usr/bin/visage:19:in `load'
        from /usr/bin/visage:19
```

**Comment by auxesis** [comment]
Hey there. Looks like it may be a bug with how Visage is invoking Rack. 

I'm out of town on holidays atm but will take a closer look on Friday when I return. 

Thanks for your patience. :-)

**Comment by auxesis** [comment]
Now that I think of it, in the mean time you should be able to run Visage through Passenger without any trouble. 

You can generate an Apache vhost config with 'visage genapache'.

**Comment by ghost** [comment]
The same error shows up when I run it through visage.

:(

**Comment by ghost** [comment]
Didn't mean to close this bug. lol

**Comment by ghost** [comment]
The problem seems to be the 1.2.1 version of rack gem, which implements a escape_html method that seems to be broken. Downgrading it to 1.2.0 allows it to run on passenger.

The mogrel version is still broken, thou. Here's the problem:
/usr/lib/ruby/gems/1.8/gems/rack-1.2.0/lib/rack/server.rb:228: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/rack-1.2.0/lib/rack/handler/mongrel.rb:10:in `initialize': wrong number of arguments (5 for 4) (ArgumentError)
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.0/lib/rack/handler/mongrel.rb:10:in`new'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.0/lib/rack/handler/mongrel.rb:10:in `run'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.2.0/lib/rack/server.rb:213:in`start'
        from /usr/lib/ruby/gems/1.8/gems/visage-app-0.2.1/bin/visage:28
        from /usr/bin/visage:19:in `load'
        from /usr/bin/visage:19

**Comment by auxesis** [comment]
I've tried a couple of different methods, but I can't work out how to reproduce this with Mongrel. Maybe it's a rack/Mongrel version mismatch on your machine?

As an untested work around, I've specified that Rack should boot with  Webrick in visage-app-0.2.7. 

Let me know if this doesn't fix it.
