### ISSUE TITLE
Problems seeing data with collectd 4.10

### ISSUE THREAD

**Issue by kwellman** [auxesis/visage#24]
I can't see the available hosts and metrics, and graphs don't show up after upgrading to collectd 4.10. Seems to work fine with old version of visage (0.1.8) or with old version of collectd.

I triple checked the rrddir setting in init.rb to make sure it points to the directory containing the data ("/opt/collectd/var/lib/collectd").

**Comment by auxesis** [comment]
Thanks for reporting this. 

I'll see if I can reproduce later today.

**Comment by auxesis** [comment]
Ok, I worked out where this bug is: I got lazy and didn't use the global config option throughout the code, so there are still some references to /var/lib/collectd. 

Now to fix.

**Comment by kwellman** [comment]
Great! Looking forward to using the new version.

**Comment by auxesis** [comment]
I believe I've fixed this in 0.2.5. 

Let me know if this release doesn't fix it!

**Comment by kwellman** [comment]
Fixed!

Works great.
