### ISSUE TITLE
Change color within plugins-colors.yaml failed

### ISSUE THREAD

**Issue by zarx** [auxesis/visage#3]
Trying to edit plugins-colors.yaml for disk section because all disk merged, time, ops, octets using only two colors which is "#73d216" & "#cc0000" (default Visage installation).

However, when I try to change the time-write color to "#3465a4" (blue), restart Apache+Passenger and F5 to reload the page, the time-write color is not blue ("#3465a4") but dark red ("#73d216") although the plugins-colors.yaml used "#3465a4" .

Does it something to do with fallback-colors.yaml or something else?

**Comment by auxesis** [comment]
Hi zarx, 
Thanks for reporting this bug. I can reproduce, however when I edit time-write I get octets-write displaying in blue (an index error in the JS, I think). 

Do you see something similar, or no blue at all?

**Comment by auxesis** [comment]
Hi zarx,
I'm pretty sure i've fixed this bug. If you could pull the latest code and test, that would be great.
