### ISSUE TITLE
Installing on ubuntu 10.10

### ISSUE THREAD

**Issue by vroy** [auxesis/visage#30]
I'm using http://rvm.beginrescueend.com/ if it matters at all. When I run `visage start` I see the message but the process does not stay up. It's obviously not accessible from the browser since the app is not running anymore.

I'm guessing I've done something wrong while installing, it was a bit problematic and I don't remember exactly everything I did, but I can list the software versions I think are necessary, maybe someone can help?
- ruby -v #=> ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]
- gem -v #=> 1.3.7
- The gems are all installed according to the dependencies.
- rrdtool #=> RRDtool 1.4.3  Copyright 1997-2009 by Tobias Oetiker tobi@oetiker.ch    Compiled Aug 16 2010 10:48:56
- collectd #=> 4.10.1

I might be missing something, if you need anything else to troubleshoot, please let me know. I'm really looking forward to testing this out and if it works well for my desktop, using it in our production environment.

Thanks,
exloid

**Comment by auxesis** [comment]
Hey there,
Thanks for reporting this bug - I very much appreciate that you've taken the time and effort to help improve Visage. 

Can you trigger the same behaviour if you're not using RVM? Also, what's the return code of `visage start` when it exits?

Also I've release a new version today (0.3.0) which is unlikely to fix the issue, but you never know. :-)

**Comment by vroy** [comment]
No problem! I really want to use collectd and RRDtool, visage seems like a good start. I updated to 0.3.0 and the return code of `visage start` on exit is 1. One of the reason I want to use rvm is that I won't need to install rubies through apt or compile them manually. I'd rather not make a standard install and screw anything up (to be honest, I suck at installing software).

Is there a way I can see the stack trace or enable some extra logging? I didn't take the time to look at any of the code yet, it might be my small weekend project.

Let me know what you think, I'll be glad to help with anything if I can eventually use it!

**Comment by auxesis** [comment]
I've seen this sort of problem before when Ruby can't load a C extension. I'm guessing there's something weird with how RVM is managing load paths. 

Can you try running [this quick tester script](http://gist.github.com/629665) and let me know what output you get?

**Comment by vroy** [comment]
I tried your tester script and it doesn't work (no output). When I try the requires in irb, it exits irb after `require 'errand'`

**Comment by auxesis** [comment]
Ahah! That means that RRDtool Ruby bindings aren't being loaded correctly. 

I'm guessing you have the librrd-ruby / ruby-rrdtool packages installed?

What happens if you fire up irb and run `require 'RRD`?

**Comment by vroy** [comment]
Ohh that was a stupid mistake from my part. I didn't install librrd-ruby because I thought it was a gem installed through apt. One of the reasons I want to use rvm is to stay clear of that. So I installed librrd-ruby and the tester script is working.

I couldn't use it on the first start, but I was able to set it up after restarting the app and manually editing `gems/visage-app-0.3.0/lib/visage/config/profiles.yaml`. Somehow the config got corrupted and it couldn't be loaded. When I click on the <create> button to create a profile it sends me to a page that doesn't exist so it looks like there's a problem with the creation of profiles.

**Comment by vroy** [comment]
At least on the first profile I tried it didn't work. I just created a new profile and it worked and sent me to the right page.

**Comment by vroy** [comment]
Thanks a lot, I'll play around and will definitely let you know if I have any more questions. So far it's awesome :)

**Comment by auxesis** [comment]
No worries. :-)

I think the profiles creation bug may have been related to the general Ruby C extension loading one. 

Hope you enjoy using Visage! Let me know if you find any more bugs or have any feature requests and I'll get them sorted.

**Comment by auxesis** [comment]
I should add, Bernd Ahlers is working on a RRD C extension gem called [librrd-ruby](http://github.com/bernd/librrd-ruby). I'll be looking at switching to it for Visage, but it would still require the RRDtool headers installed.
