### ISSUE TITLE
Creating profiles is broken

### ISSUE THREAD

**Issue by ycros** [auxesis/visage#42]
Tested with both visage-app start and running on phusion passenger.

Steps to reproduce:
1. Go to profile builder
2. Enter hosts, metrics
3. Enter profile name, click create
4. Browser redirects to 404 at /profiles/<entered profilename>

Expected:
Profile should work.

Interestingly, the underlying profiles.yaml DOES get populated with data:

```

---
webserver:
  :metrics: apache*/*
  :hosts: goliath.devfu.com.au
  :url: webserver
  :profile_name: webserver
```

I'll have a poke at the code, and see if I can reproduce on my dev machine.

**Comment by auxesis** [comment]
There's a race condition. 

Are you running 0.3.x or 0.9.0.pre? I believe I've fixed this issue in 0.9.0.pre.

**Comment by ycros** [comment]
I'm running 0.3.3, where's 0.9.0.pre? I don't see it on github.

**Comment by auxesis** [comment]
Sorry, documentation on this stuff is thin at best. :-(

Lives in the highcharts branch on GitHub. 

Installable with:

gem install visage-app --prerelease

**Comment by ufm** [comment]
in 0.9.0.pre:

NoMethodError at /builder
undefined method `[]=' for nil:NilClass

```
* file: profile.rb
* location: save
* line: 71
```

**Comment by mherweg** [comment]
Steps to reproduce:
1. Go to profile builder
2. Enter hosts, metrics
3. Enter profile name, click create

I can enter hosts, metrics
but then.. where can I enter the profile name ? i don't see any "create" button.

**Comment by auxesis** [comment]
Hit enter when you've entered the hosts + metrics. This will submit the form, and the profile name will appear. 

I've designed for keyboard input, and have hidden the submit buttons. 

Probably worth adding them in.

**Comment by bmatheny** [comment]
I ran into the undefined method issue, looks like a ruby version issue. I'm using 1.8.7 and resolved it by changing self.load (or self.whatever) references to the fully qualified name.
