### ISSUE TITLE
Unable to create profile in visage 0.9.0-pre1

### ISSUE THREAD

**Issue by ycros** [auxesis/visage#43]
I get this exception:

```
NoMethodError - undefined method `[]=' for nil:NilClass:
 /home/collectd/.gem/ruby/1.8/gems/visage-app-0.9.0.pre1/lib/visage-app/profile.rb:71:in `save'
 /home/collectd/.gem/ruby/1.8/gems/visage-app-0.9.0.pre1/lib/visage-app.rb:60:in `GET /builder'
```

Looking at that line of code, it seems like it's because there's nothing in the file to start with?

**Comment by jro** [comment]
seems that way.  this change fixes it for me.

<pre>

--- a/lib/visage-app/profile.rb
+++ b/lib/visage-app/profile.rb
@@ -67,7 +67,7 @@ module Visage
                   :url => @options[:profile_name].downcase.gsub(/[^\w]+/, "+") }
 
         # Save it.
-        profiles = self.load
+        profiles = self.load || {}
         profiles[attrs[:url]] = attrs
 
         Visage::Config::File.open('profiles.yaml') do |file|
</pre>

**Comment by auxesis** [comment]
I believe this was fixed in cc879fdc9b43cb0506b0c8d8b30e9d54ea81d0cf, which is now in visage-app 0.9.0.pre2

**Comment by ycros** [comment]
I'll take another look at it, maybe over LCA. (when I can annoy you about bugs in person ;))

**Comment by auxesis** [comment]
Heh, sounds... good? :-)
