### ISSUE TITLE
Graph labels are mostly null

### ISSUE THREAD

**Issue by jro** [auxesis/visage#49]
For most of my graphs, I get an empty string as the line label.  It seems to be coming from line 17, which I think is a bug.

<pre>
name = plugin == "irq" ? name.replace(/^/, 'irq ') : ''
</pre>

To me this says, make my name "irq whatever" if my plugin is irq, OR make my title empty string.  

So, I've replaced it as 

<pre>
name = plugin == "irq" ? name.replace(/^/, 'irq ') : name
</pre>

Which works great for most of my graphs, but some of the ones specifically coded like load and ^disk get messed up.  My suspicion is that you added the specific code based on the above bug.  With load and disk I can remove the specific code and it works great.  Unfortunately, I don't have all the collectd metrics to cover all the specific cases, so that makes it hard for me to have confidence that you can pull my patch without issue.

**Comment by auxesis** [comment]
This is fixed in bzed/visage@a27923046689b1b5e8a5a2f939701ac5f8a204b1, and I'll apply it once the style is cleaned up a tad.

**Comment by auxesis** [comment]
Merged, available in 0.9.0 final, closing.
