### ISSUE TITLE
uninitialized constant CollectdJSON::RRDtool

### ISSUE THREAD

**Issue by mdelves** [auxesis/visage#5]
When running visage (after replacing gem references for RRDtool to errand) I get the following error.
NameError: uninitialized constant CollectdJSON::RRDtool
        ./lib/collectd-json.rb:29:in `json'
        ./lib/collectd-json.rb:28:in`map'
        ./lib/collectd-json.rb:28:in `json'
        ./visage.rb:69:in`GET (?-mix:\/data\/([^\/]+)\/([^\/]+)(\/([^\/]+))*)'
        /usr/lib/ruby/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:779:in `call'

Also, I have to run visage using "ruby ./visage.rb" which runs sinatra on port 4567 rather than using shotgun which doesn't allow communication to port 9393 (I have the firewall turned off).

**Comment by auxesis** [comment]
Errand isn't API compatible with RubyRRDtool, so this isn't going to work.

I'll release an updated version of Visage (that uses Errand) in the next few days when I have a moment between travel.
