### ISSUE TITLE
Weird Axis labelling

### ISSUE THREAD

**Issue by bzed** [auxesis/visage#53]
Hi,

imho 1K should be the same as 1000, so the labeling as shown in http://devel.recluse.de/~bzed/.publish/2011-01-24-xc5akDBR8kA/axis_label_bug.png looks pretty weird to me.

Cheers,

Bernd

**Comment by auxesis** [comment]
I'm curious - what does the rest of that Y axis look like?

**Comment by bzed** [comment]
In this case it was something like 1K, 1000, 800, 600, 400, ... and so on.
But I've seen the same issue with steps of 250.... zooming in and our fixes the issue.

**Comment by auxesis** [comment]
Ok, I see what you're getting at. 

How do you expect the Y-axis labels to appear with data like that?

**Comment by bzed** [comment]
I'd expect it to show 1.2K, 1000, 800, 600, 400 ... Or instead of introducing the K here show 1200. I guess the best option would be to have K/M/G values everywhere or not at all. 1200, 1000, 800, 600 would still be fine and readable, but 1K, 1000, ... is just wrong :)

**Comment by auxesis** [comment]
Having a consistent unit makes sense. 

I should be able to come up with a patch pretty quickly.

**Comment by auxesis** [comment]
Turns out the fix wasn't that trivial! 

New code in 0.9.6 - would appreciate any and all feedback you may have.
