### ISSUE TITLE
Clarify HighCharts license

### ISSUE THREAD

**Issue by bzed** [auxesis/visage#54]
Please clarify the license under which the highcharts library is shipped within your project. In LICENSE you mention
<code>Visage is distributed with Highcharts. Torstein Hønsi has kindly granted
permission to distribute Highcharts under the GPL as part of Visage.</code>

while the highcharts files only point to their CC-3-nc / commercial license.
Also it is not mentioned under which version of the GPL exactly the highcharts code is being shipped.

**Comment by auxesis** [comment]
Fixed in 58fdbcc9d3b1ccbc8101a1e3fb8cf02303ca91ac.
