### ISSUE TITLE
CentOS 5.5 x86_64, visage doesn't start, no error/debug messages

### ISSUE THREAD

**Issue by joemiller** [auxesis/visage#58]
I have followed the directions in the README and on the website for installing visage on centos but I cannot get it to run correctly.  It looks like it starts OK but nothing is listening on port 9292 and no ruby procs are running.

Is there a way to make visage spit out more debug or error messages so i can figure out what's wrong?  

I ran it through strace but didn't see much other than it may be looking for RRD.so in the ruby gem paths and cannot find it.  Not sure if this is the real culprit though.

```
$ visage-app start
 _    ___
| |  / (_)________ _____ ____
| | / / / ___/ __ `/ __ `/ _ \
| |/ / (__  ) /_/ / /_/ /  __/
|___/_/____/\__,_/\__, /\___/
                 /____/

will be running at http://host:9292/

$ telnet localhost 9292
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host: Connection refused
```

**Comment by auxesis** [comment]
Hi joemiller,
Thanks for reporting this bug. I'll have a look and see if I can reproduce. 

Visage shouldn't actually exit like that - `visage-app start` runs in the foreground. My guess is that it's some sort of silent RRD library error. 

It's a dumb question, but I assume you've done a `yum install -y ruby-RRDtool`?

Cheers!

**Comment by joemiller** [comment]
I did do that, but it installed RRDtool.so and not the RRD.so that the strace output seemed to indicate it was looking for.

I ended up fixing this by removing the ruby-RRDtool and rrdtool rpm's (I believe they had come from the epel yum repos) and installed rrdtool-1.2.30-_rpm and ruby-rrdtool-1.2.30-_rpm from http://packages.sw.be/rrdtool/ .. The 1.2.x version seems to work fine with the collectd*rpm's I have installed (also from epel, i believe) but the 1.3.x and 1.4.x rpm's from that repo did not.

**Comment by auxesis** [comment]
Thanks for reporting that. 

I'll have a dig into Errand on RHEL and see if I can reproduce.

**Comment by yrcjaya** [comment]
I did encountered the same problem, but I changed the line 
`require 'RRD'`
to `require 'RRDtool'` in errand.rb

It works fine now, I guess you just have first try to load RRD on LoadError try RRDtool

**Comment by yrcjaya** [comment]
sorry changing the line brings up another problem.

Anyway ruby-RRDtool package is the wrong package.
Install rrdtool-ruby package from the EPEL repo it works fine

**Comment by aamirdb** [comment]
I am also having the same issue - 

[root@localhost lib]# telnet localhost 9292
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused

I checked by turning off iptables and its still there. After configuring the virtualhost in apache and installing passenger, I m getting Internal server error -

Here is what the logs say -

Errno::ENOTDIR - Not a directory - /usr/bin/visage-app/profiles.yaml:
 /usr/lib/ruby/1.8/fileutils.rb:1036:in `utime'
 /usr/lib/ruby/1.8/fileutils.rb:1036:in`touch'
 /usr/lib/ruby/1.8/fileutils.rb:1033:in `each'
 /usr/lib/ruby/1.8/fileutils.rb:1033:in`touch'
 /usr/lib/ruby/gems/1.8/gems/visage-app-0.9.4/lib/visage-app/config/file.rb:26:in `load'
 /usr/lib/ruby/gems/1.8/gems/visage-app-0.9.4/lib/visage-app/profile.rb:15:in`load'
 /usr/lib/ruby/gems/1.8/gems/visage-app-0.9.4/lib/visage-app/profile.rb:26:in `all'
 /usr/lib/ruby/gems/1.8/gems/visage-app-0.9.4/lib/visage-app.rb:48:in`GET /profiles'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:1063:in `call'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:1063:in`compile!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:649:in `instance_eval'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:649:in`route_eval'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:633:in `route!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:681:in`process_route'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:678:in `catch'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:678:in`process_route'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:632:in `route!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:631:in`each'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:631:in `route!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:766:in`dispatch!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:559:in `call!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:731:in`instance_eval'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:731:in `invoke'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:731:in`catch'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:731:in `invoke'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:559:in`call!'
 /usr/lib/ruby/gems/1.8/gems/sinatra-1.1.3/lib/sinatra/base.rb:544:in `call'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/rack/request_handler.rb:91:in`process_request'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/abstract_request_handler.rb:206:in `main_loop'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/rack/application_spawner.rb:118:in`run'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/rack/application_spawner.rb:69:in `spawn_application'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/utils.rb:182:in`safe_fork'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/rack/application_spawner.rb:62:in `spawn_application'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/rack/application_spawner.rb:45:in`spawn_application'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/spawn_manager.rb:158:in `spawn_application'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/spawn_manager.rb:286:in`handle_spawn_application'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/abstract_server.rb:351:in `__send__'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/abstract_server.rb:351:in`main_loop'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/lib/phusion_passenger/abstract_server.rb:195:in `start_synchronously'
 /usr/lib/ruby/gems/1.8/gems/passenger-2.2.4/bin/passenger-spawn-server:61

Help me :)
