### ISSUE TITLE
require 'rubygems' missing from visage.rb

### ISSUE THREAD

**Issue by mdelves** [auxesis/visage#6]
When I attempt to run visage through the command 'ruby visage.rb' it fails to load the sinatra gem.
This is fixed by placing in the line:
require 'rubygems'

Once that has been done everything works as expected. Thanks for the updates.

**Comment by auxesis** [comment]
In development, you shouldn't be running Visage with Ruby directly - that's what shotgun is for: `shotgun visage.rb`. 

If you're certain you want to run Visage with the `ruby` binary directly, run `ruby -rubygems visage.rb`.
