### ISSUE TITLE
Load profiles from multiple files

### ISSUE THREAD

**Issue by sciurus** [auxesis/visage#62]
Currently all profiles are stored in a single configuration file, profiles.yaml. It would be nice if profiles could be loaded from multiple files; this would make generating visage configuration from other tools like puppet simpler.

**Comment by auxesis** [comment]
Good call. I think this makes a lot if sense. 

Do you think a file per profile would be appropriate, or just make it arbitrary?

**Comment by sciurus** [comment]
Just making it arbitrary would be nicest.

**Comment by auxesis** [comment]
This is being [actively worked on](https://github.com/auxesis/visage/blob/master/lib/visage-app/models/profile.rb) for Visage 3.0. 

The profiles are being represented be a proper model that uses ActiveModel for all the validations + serialisations, so changing the implementation to use multiple files is pretty straight forward. 

The main motivation for doing this is to make testing a little easier, but it'll definitely help in the config management scenario you outlined above @sciurus.

**Comment by auxesis** [comment]
This is implemented as of 191cca0fdcdd661349c09ca1f634d9ea41f9a52b and ff635d4e95bada977a77ec829531bb4d9ec39c7a. 

Closing.
