### ISSUE TITLE
a simple change on install instructions given on website

### ISSUE THREAD

**Issue by greenmang0** [auxesis/visage#72]
I would like to suggest a simple change on website's - http://auxesis.github.com/visage/ - Install Section

gem install visage-app sinatra

cause without sinatra it spits out an error
 ERROR:  Error installing visage-app: visage-app requires sinatra (~> 1.1.3, runtime)

**Comment by empanda** [comment]
I just ran into this bug.

As a non-rubyist, this was a little confusing because I thought that `gem` would manage the dependencies for me.

**Comment by greenmang0** [comment]
cool, that it helped you :), i also figured out that it requires order to install, 

gem install sinatra visage-app
