### ISSUE TITLE
no such file to load -- RRD (LoadError)

### ISSUE THREAD

**Issue by icy** [auxesis/visage#76]
Hi,

I am trying to install `visage` on Arch Linux, and I don't know how to install RRD support. Please help. Thank you very much.

``` ruby
visage-app start
....

/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- RRD (LoadError)
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /home/rubygems/1.8/gems/errand-0.7.3/lib/errand.rb:4
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /home/rubygems/1.8/gems/visage-app-1.0.0/lib/visage-app/collectd/json.rb:6
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /home/rubygems/1.8/gems/visage-app-1.0.0/lib/visage-app.rb:14
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /home/rubygems/1.8/gems/visage-app-1.0.0/bin/visage-app:26
        from /home/rubygems/1.8/bin/visage-app:19:in `load'
        from /home/rubygems/1.8/bin/visage-app:19
```

**Comment by icy** [comment]
Oh, I've suddenly found that I had to install the library `git://github.com/auxesis/librrd-ruby.git` by building gem manually. Feel free to add the note to your documentation. Thank you!

**Comment by auxesis** [comment]
Hi there! Alternatively, you can `pacman -S rrdtool`, which will install the Ruby bindings too.

**Comment by icy** [comment]
Thanks,

"pacman -S rrdtool" installs the gem for ruby-1.9.1, which is useless if system uses another ruby alternative.

**Comment by auxesis** [comment]
Oh, that's a bummer. @bernd's librrd-ruby should do what you need though.

**Comment by bernd** [comment]
The visage README already contains a pointer to install the librrd gem.

**Comment by icy** [comment]
Yes I've seen that. Though the homepage didn't mention and it took me some minutes to figure it out :D Instead of showing some distro-specific commands, why not state a common thing likes `"visage-app" requires "librrd" (from http://foo.bar/)` ? It makes more sense, IMHO. BTW, if the gem "visage-app" knows its dependencies at installing time , it would be perfect (I meant, "gem install visage-app" will install its all dependencies)

Thank you again.

**Comment by auxesis** [comment]
I agree that the whole situation is suboptimal. 

The `librrd` gem requires that various RRD build dependencies are installed. 

It's significantly easier to ask people to install their distribution's `rrdtool` package with Ruby bindings than ask them to install a whole compiler toolchain. Hence the lack of documentation on the Visage web page about the compiling-from-source install method. 

Ideally Visage can switch to an FFI version of the RRD bindings. This would mean the user won't need to install Ruby rrdtool bindings through their package manager, and they won't need to build anything from source. Would also mean Visage would run on JRuby without any problems.

**Comment by icy** [comment]
I agree :) Thank you very much.

**Comment by bernd** [comment]
@auxesis I agree. Using the FFI RRD version would make it way easier. :)

**Comment by ChrisLundquist** [comment]
https://github.com/morellon/rrd-ffi
