### ISSUE TITLE
Stacked graphs

### ISSUE THREAD

**Issue by JarleB** [auxesis/visage#77]
I have made some custom graphs using som rather lengthy rrdtool-graph-commands that aggregates a lot of datasources from collectd's rrdfiles and stack them on top of each other using STACK and AREA in rrdtool graph. 

I very much like the concept of visage-app and wonder if the same thing could be achieved using visage ?

Best rgds
Jarle Bjørgeengen

**Comment by ChrisLundquist** [comment]
This should be fixed by #91
