### ISSUE TITLE
Gem install failed on CentOS 5.6 using collectd.x86_64

### ISSUE THREAD

**Issue by noahcampbell** [auxesis/visage#78]
I changed the install step slightly:

```
sudo yum install -y ruby-RRDtool ruby rubygems collectd.x86_64
```

because collectd.i386 requires python2.4 which is missing from my repos for some reason:

```
collectd-4.10.3-1.el5.i386 from epel has depsolving problems
  --> Missing Dependency: libpython2.4.so.1.0 is needed by package collectd-4.10.3-1.el5.i386 (epel)
```

However, when I run sudo gem install visage-app

```
/usr/bin/ruby extconf.rb install visage-app
can't find header files for ruby.
```

**Comment by JarleB** [comment]
Have you tried install visage-app through rvm ?

https://github.com/auxesis/visage/wiki/Installing-visage-app-using-rvm

**Comment by gavincarr** [comment]
I ran into the same issue with collectd.x86_64 on CentOS6 x86_64, fwiw. You need to install ruby-devel for the ruby headers.

**Comment by auxesis** [comment]
Hi @noahcampbell, I've updated the Visage install instructions for CentOS5/RHEL5 as part of the Visage 2.0.0 release to cater to this bug. 

Unfortunately yajl-ruby requires a newer version of Ruby (>= 1.8.6) than what is provided with RHEL5 (1.8.5), so the recommendation for Visage users is to use the Ruby Enterprise Edition packages [provided by Endpoint](https://packages.endpoint.com/). 

Per @gavincarr's advice, I've updated the CentOS6/RHEL6 installation instructions to include installing `ruby-devel`
