### ISSUE TITLE
View a year of data

### ISSUE THREAD

**Issue by sciurus** [auxesis/visage#80]
The maximum timespan you can choose to display in visage is one month. By default, collectd stores data for one year. Visage should be able to display this.

**Comment by auxesis** [comment]
Agreed. This should be pretty easy to implement too. 

Check out: https://github.com/auxesis/visage/blob/master/lib/visage-app/public/javascripts/graph.js#L494

All you need to do is add an entry in there. 

Feel like submitting a patch? :-)

**Comment by auxesis** [comment]
This was resolved in #80.
