### ISSUE TITLE
Re-create visage as an API and app platform

### ISSUE THREAD

**Issue by rasmusbergpalm** [auxesis/visage#85]
I know, it's quite a mouthfull, but I think it's easier than you'd think and the benefits are gigantonourmeous :)
I sat down the other day and analyzed what i really wanted from a general data analysis tool and here's what i came up with:
- Open source
- Smart DB tech for storing large amounts of data (eg. RRD)
- API to input/output data
- App platform
- classes to interface with the most common data creators  (eg. PHP/ruby/MySQL etc.)
- eat-your-own-dog-food API based frontend

I came up with this list based on the premise that data-junkies will never be satisfied with any one solution. Some will try some advanced data analysis methods, some want visualizations, some just want a data storage. BUT, data-junkies are hackers, so if we give them a great API and an app-platform, they'll create what they need themselves. I imagine that the current visage visualiztion features would be bundled as a set of core apps.
I really think there's a big and growing userbase for this kind of app, as 'big data', 'data scientists' and 'business intelligience' are the new buzzwords in silicon valley. Maybe this needs a new project entirely, maybe we can use visage as a starting point. Let me know what you think.

Cheers, Rasmus.

**Comment by auxesis** [comment]
We're getting pretty close to that with Visage 3.0 now. Specifically: 
- [Abstracted backends](https://github.com/auxesis/visage/blob/master/lib/visage-app/data.rb) for [different](https://github.com/auxesis/visage/blob/master/lib/visage-app/data/rrd.rb) data [sources](https://github.com/auxesis/visage/blob/master/lib/visage-app/data/mock.rb).
- An [API for querying data](https://github.com/auxesis/visage/blob/master/man/visage-api.5.ronn), that is independent of the backend used.
- The Visage 3.0 frontend is Backbone based, and uses all of the public APIs. 

Does this match up with what you were thinking, @rasmusbergpalm?
