### ISSUE TITLE
update gem deps please?

### ISSUE THREAD

**Issue by swills** [auxesis/visage#89]
Hi,

Would you be willing to update the gem deps? Support for sinatra 1.3.x, tilt 1.3.x, haml 3.1.x and yajl 1.1.x would be great.

Thanks,
Steve

**Comment by halkeye** [comment]
Yea, I'm getting

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: visage-app requires tilt (~> 1.2.2)

There is no indication on the front page on how to work around it, so something should be done.

If anyone else finds this, it should be "gem install tilt -v 1.2.2" then install visage-app

**Comment by jhanssen** [comment]
@halkeye Thanks! Wasn't able to figure out how to fix this before I saw your reply.

**Comment by mbailey** [comment]
Yes, please update gem deps. gem install failed on ubuntu 10.0.4.4-server

**Comment by auxesis** [comment]
I've bumped up the dependencies in d962007da2462a5f4ca8a9754b072d30bf6c3594, which is part of the Visage 2.0 release I'm putting out now. 

Thanks for your patience, all! Resolving.
