### ISSUE TITLE
difficulty selecting Hosts and Metrics in Builder

### ISSUE THREAD

**Issue by jessereynolds** [auxesis/visage#96]
When creating a new profile in the builder, it can be difficult to select hosts and metrics from their drop down live search results due to the following issues:

If you move the mouse over the live search results and then away again, then you cannot select anything from the list. 

If you select a host, then use the return key to move to the metrics, the full hosts drop down selector is left still shown. Similarly if you option-tab from metrics back to hosts, all the metrics are left displayed in the drop down. Fix for this one would be to always hide the drop down selector when the field is not in focus (on blur). 

Arrowing down the list goes off the bottom of the screen without the browser scrolling so you can see where you are. 

Page Down / Up does not work to scroll the search results, would be nice if it did.

**Comment by auxesis** [comment]
These problems pretty much go away in 3.0, as the builder is brand new.
