### ISSUE TITLE
Regex's in the Builder searchers don't seem to work

### ISSUE THREAD

**Issue by jessereynolds** [auxesis/visage#97]
As I understand, I should be able to enter ".*" (ie dot star) into a searcher to have it select everything, but this produces a javascript error:

Uncaught TypeError: Cannot call method 'get' of null
Class.selectbuilder.js:262
wrapper.extend.$ownermootools-core-1.4.0-full-compat.js:1643
(anonymous function)builder.js:92
(anonymous function)mootools-core-1.4.0-full-compat.js:947
defnmootools-core-1.4.0-full-compat.js:4233

Similarly the .\* pattern within other text, eg "cpu._/._" also fails.

**Comment by aussielunix** [comment]
I was able to get it working but it's not a smooth ride.
I didn't use a regex as such though.
Just by typing _mysql_ and nothing else it selected all metrics that contained _mysql_
This is a huge list on my system and appeared to do nothing for around 50-90 seconds then just worked as expected.

Cheers
Mick
@aussielunix

**Comment by auxesis** [comment]
The current iteration of the builder goes away in 3.0. 

Resolving.
